# Membuat Matrix

In [2]:
import numpy as np

In [2]:
arr = [[1,2], [3, 4]]

In [3]:
np.array(arr)

array([[1, 2],
       [3, 4]])

In [3]:
import torch

In [5]:
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

# Membuat Matrix dengan nilai yang sudah ditentukan

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [10]:
torch.ones((2,2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [11]:
np.random.randn(2,2)

array([[-0.51410163, -0.62778903],
       [ 0.72118064,  2.33603135]])

In [12]:
torch.randn(2,2)


 0.4319  0.2975
-1.6510 -0.1529
[torch.FloatTensor of size 2x2]

# Mengenal Seed

In [13]:
np.random.seed(0)
np.random.randn(2,2)

array([[1.76405235, 0.40015721],
       [0.97873798, 2.2408932 ]])

In [15]:
# Nilai random yang diberikan konsisten jika kita mengatur dari seed
np.random.seed(0)
np.random.randn(2,2)

array([[1.76405235, 0.40015721],
       [0.97873798, 2.2408932 ]])

In [16]:
# Tidak menggunakan seed
np.random.randn(2,2)

array([[ 1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721]])

In [17]:
np.random.randn(2,2)

array([[-0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351]])

In [18]:
torch.manual_seed(0)
torch.randn(2,2)


 1.5410 -0.2934
-2.1788  0.5684
[torch.FloatTensor of size 2x2]

In [19]:
torch.manual_seed(0)
torch.randn(2,2)


 1.5410 -0.2934
-2.1788  0.5684
[torch.FloatTensor of size 2x2]

In [20]:
torch.randn(2,2)


-1.0845 -1.3986
 0.4033  0.8380
[torch.FloatTensor of size 2x2]

In [21]:
torch.randn(2,2)


-0.7193 -0.4033
-0.5966  0.1820
[torch.FloatTensor of size 2x2]

# Penghubung NumPy dan PyTorch

In [22]:
np_array = np.ones((2,2))

In [23]:
np_array

array([[1., 1.],
       [1., 1.]])

In [24]:
type(np_array)

numpy.ndarray

In [25]:
torch_tensor = torch.from_numpy(np_array)

In [26]:
torch_tensor


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [27]:
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

In [29]:
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [30]:
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [31]:
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [32]:
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [33]:
torch_tensor = torch.ones((2,2))

In [34]:
type(torch_tensor)

torch.FloatTensor

In [35]:
torch_tensor.numpy()

array([[1., 1.],
       [1., 1.]], dtype=float32)

# CPU and GPU

In [36]:
tensor_cpu = torch.ones(2,2)

In [37]:
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [38]:
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

# Operasi Tensor

In [19]:
a = torch.ones((2,3))

In [20]:
a


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]

In [21]:
a.size()

torch.Size([2, 3])

In [23]:
a.view(3,2)


 1  1
 1  1
 1  1
[torch.FloatTensor of size 3x2]

In [25]:
a.view(6)


 1
 1
 1
 1
 1
 1
[torch.FloatTensor of size 6]

# Operasi Tiap Elemen

## Penambahan

In [26]:
a = torch.ones((2,2))
b = torch.ones((2,2))

In [28]:
c = a + b

In [29]:
c


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [30]:
a.add(b)


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [32]:
torch.add(a,b)


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [33]:
# Inplace Operation
print('Tensor Lama')
print('-----------')
print(c)

c.add_(b)
print('')
print('Tensor Baru')
print('-----------')
print(c)

Tensor Lama
-----------

 2  2
 2  2
[torch.FloatTensor of size 2x2]


Tensor Baru
-----------

 3  3
 3  3
[torch.FloatTensor of size 2x2]



## Pengurangan

In [34]:
a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [35]:
a.sub(b)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [36]:
c


 3  3
 3  3
[torch.FloatTensor of size 2x2]

In [37]:
c.sub_(a)
c


 2  2
 2  2
[torch.FloatTensor of size 2x2]

# Perkalian

In [41]:
x = torch.Tensor([[2,2],[2,2]])
y = torch.Tensor([[3,3], [9,4]])

In [42]:
x * y


  6   6
 18   8
[torch.FloatTensor of size 2x2]

In [43]:
x.mul(y)


  6   6
 18   8
[torch.FloatTensor of size 2x2]

In [44]:
x.mul_(y)
x


  6   6
 18   8
[torch.FloatTensor of size 2x2]

## Pembagian

In [47]:
x = torch.Tensor([[0, 0],[0,0]])
y = torch.Tensor([[2,2],[2,2]])


In [49]:
x / y


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [50]:
x.div(y)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [51]:
x.div_(y)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [52]:
x


 0  0
 0  0
[torch.FloatTensor of size 2x2]

## Rata - Rata

In [53]:
tensor = torch.Tensor([1,2,3,4,5,6,7,8,9,10])

In [54]:
tensort


  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
[torch.FloatTensor of size 10]

In [55]:
tensor.size()

torch.Size([10])

In [56]:
tensor.view(5,2)


  1   2
  3   4
  5   6
  7   8
  9  10
[torch.FloatTensor of size 5x2]

In [60]:
tensor.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [61]:
tensor.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [62]:
tensor = torch.Tensor([[1,2,3,4,5,6,7,8,9,10], [1,2,3,4,5,6,7,8,9,10]])

In [63]:
tensor


    1     2     3     4     5     6     7     8     9    10
    1     2     3     4     5     6     7     8     9    10
[torch.FloatTensor of size 2x10]

In [68]:
tensor.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

In [69]:
tensor.std(dim=1)


 3.0277
 3.0277
[torch.FloatTensor of size 2]